#!/bin/bash
cd /root/workspace/DisasterRecord
/root/workspace/DisasterRecord/drEnv /root/workspace/DisasterRecord/make.sh $1 >> /var/log/DR.log 2>&1 &
FOO_PID=$!
echo $FOO_PID > /root/drService_Backend.pid