#!/bin/bash
TS=$(date -u)
echo -e "[$TS] -->KILLING DRECORD INFERENCE SERVICE\n" >> /var/log/DR.log 2>&1 &
pid=$(cat /root/inf.pid)
while true; do
  cpid=$(pgrep -P $pid)
  if [[ $cpid ]]; then
    echo $cpid
    kill $cpid
    pid=$cpid
  else
    break
  fi
done
echo $pid
kill $pid