#!/bin/bash
TS=$(date -u)
echo -e "[$TS] -->KILLING DRECORD TWITTER STREAM MANAGER SERVICE\n" >> /var/log/DR.log 2>&1 &
pid=$(cat /root/tstream_man.pid)
while true; do
  cpid=$(pgrep -P $pid)
  if [[ $cpid ]]; then
    pid=$cpid
    echo $cpid
    kill $cpid
  else
    break
  fi
done
echo $pid
kill $pid