#!/bin/bash
TS=$(date -u)
echo -e "[$TS] -->KILLING ALL SERVICES\n" >> /var/log/DR.log 2>&1 &
pid=$(cat /root/drService_All.pid)
while true; do
  cpid=$(pgrep -P $pid)
  if [[ $cpid ]]; then
    echo $cpid
    kill $cpid
    pid=$cpid
  else
    break
  fi
done
echo $pid
kill $pid

/root/killDR-Frontend >> /var/log/DR.log 2>&1 &
/root/killINF >> /var/log/DR.log 2>&1 &
/root/killOBJ >> /var/log/DR.log 2>&1 &
/root/killTC >> /var/log/DR.log 2>&1 &
/root/killAPI >> /var/log/DR.log 2>&1 &
/root/killSafetyCheck >> /var/log/DR.log 2>&1 &
/root/killTStreamMan >> /var/log/DR.log 2>&1 &