#!/bin/bash
TS=$(date -u)
echo -e "[$TS] -->STARTING DRECORD OBJECT DETECTION SERVICE\n" >> /var/log/DR.log 2>&1 &
cd /root/workspace/DisasterRecord
/root/workspace/DisasterRecord/drEnv python obj_service.py >> /var/log/DR.log 2>&1 &
FOO_PID=$!
echo $FOO_PID > /root/obj.pid