#!/bin/bash
TS=$(date -u)
echo -e "[$TS] -->STARTING DRECORD FRONTEND\n" >> /var/log/DR.log 2>&1 &
cd /root/workspace/DisasterRecord
/root/workspace/DisasterRecord/drEnv python server.py >> /var/log/DR.log 2>&1 &
FOO_PID=$!
echo $FOO_PID > /root/drService_Frontend.pid