#!/bin/bash
TS=$(date -u)
echo -e "[$TS] -->STARTING DRECORD TWITTER STREAM MANAGER SERVICE\n" >> /var/log/DR.log 2>&1 &
cd /root/workspace/DisasterRecord
/root/workspace/DisasterRecord/drEnv python tstream_man.py >> /var/log/DR.log 2>&1 &
FOO_PID=$!
echo $FOO_PID > /root/tstreamman.pid